// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCrElJMw24__8FqPxNG_T4Pusq-KUPAFx0',
    appId: '1:267308799044:android:c0b72e72b9fa637b235811',
    messagingSenderId: '267308799044',
    projectId: 'let-s-chat-99664',
    storageBucket: 'let-s-chat-99664.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8QsNggYy9gVKSBsek-wbVP-jSUg1BIv4',
    appId: '1:267308799044:ios:98c5d390560c730f235811',
    messagingSenderId: '267308799044',
    projectId: 'let-s-chat-99664',
    storageBucket: 'let-s-chat-99664.appspot.com',
    androidClientId: '267308799044-un64h655p0dtprjcvu1m5gesdmc57es6.apps.googleusercontent.com',
    iosClientId: '267308799044-l0ro378q875ofbhlqqfgcvc2lk3i69pt.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatapp',
  );
}
